name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      - name: docker
        image: docker:dind
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-playwright-tests .

    - name: Run Docker container
      run: docker run --rm my-playwright-tests
