# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Update playwright
      run: npm install -D @playwright/test@latest

    - name: Install new browsers
      run: npx playwright install

    - name: Install system dependencies
      run: npx playwright install-deps

    - name: Run Playwright tests
      run: dotnet test --filter FullyQualifiedName~DemoTestFramework.Playwright.Tests

    - name: Run Selenium tests
      run: dotnet test --filter FullyQualifiedName~DemoTestFramework.Selenium.Tests
