name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - run: dotnet build
    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net5.0/playwright.ps1 install --with-deps chromium
    - name: Run your tests
      run: dotnet test

    - name: Delete file
      run: |
        rm playwright-demo/.github/workflows/dotnet.yml

    - name: Commit and push changes
     run: |
     if [ -e "playwright-demo/.github/workflows/dotnet.yml" ]; then
     rm playwright-demo/github/workflows/dotnet.yml
     else
     echo "File not found: playwright-demo/github/workflows/dotnet.yml"
     fi
