name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - run: dotnet build
    - name: Ensure browsers are installed
      run: pwsh bin/Debug/net5.0/playwright.ps1 install --with-deps chromium
    - name: Run your tests
      run: dotnet test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
    - name: playwright-report
      path: playwright-report/
      retention-days: 7
